<?php
/*
* BaseAutoSound Default  switch languages template.
*
*@author Hrytsuk Walentun vgritsukm@gmail.com
*@copyright 2020 zevsi
*/

/** @var $block Magento\Framework\View\Element\Template */
?>
<li class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="action compare no-display" title="<?= $block->escapeHtmlAttr(__('Compare Products')); ?>"
       data-bind="attr: {'href': compareProducts().listUrl}, css: {'no-display': !compareProducts().count}"
    >
        <?= $block->escapeHtml(__('Compare Products')); ?>
        <span class="counter qty" data-bind="text: compareProducts().count, css: {'no-display': !compareProducts().count}"></span>    </a>
</li>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout(); ?>}}
</script>
