<div class="memories" data-mage-init='{"memories" : {}}'>
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">1</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">2</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">3</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">4</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">5</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">6</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">1</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">2</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">3</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">4</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">5</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="memory-cart">-->
<!--        <div class="front-face">6</div>-->
<!--        <div class="back-face"></div>-->
<!--    </div>-->
<!--    <div class="gameVictory"><p>Вітаємо ти пройшов</p></div>-->
</div>
