<?php
/*
* Autostore autos Catalog product  view details template.
*
*@author Hrytsuk Walentun vgritsukm@gmail.com
*@copyright 2020 zevsi
*/

/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) : ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" >
            <div class="tab-parent-title">
                <?php foreach ($detailedInfoGroup as $name) : ?>
                    <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    ?>
                    <?php if ($alias != 'reviews'): ?>
                            <div class="data item title"
                                 data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias); ?>">
                                <a class="data switch"
                                   tabindex="-1"
                                   data-toggle="trigger"
                                   href="#<?= $block->escapeUrl($alias); ?>"
                                   id="tab-label-<?= $block->escapeHtmlAttr($alias); ?>-title">
                                    <?= /* @noEscape */
                                    $label ?>
                                </a>
                            </div>
                     <?php endif;?>
                <?php endforeach; ?>
            </div>
            <div class="tab-parent-content">
                <?php foreach ($detailedInfoGroup as $name) : ?>
                    <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    ?>
                <?php if ($alias != 'reviews'): ?>
                    <div class="data item content <?= $block->escapeHtmlAttr($alias); ?> readmore-article"
                             aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias); ?>-title"
                             id="<?= $block->escapeHtmlAttr($alias); ?>" data-role="content">
                            <h3><?= $label, __("Goods");?></h3>
                            <?= /* @noEscape */
                            $html ?>
                    </div>
                <?endif; ?>
                <?php endforeach; ?>
            </div>
            <div class="reviews-parent">
                <?php foreach ($detailedInfoGroup as $name) : ?>
                    <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    ?>
                    <?php if ($alias === 'reviews'): ?>
                        <div class="top-content-reviews">
                            <div class="data item title"
                                 data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias); ?>">
                                <a class="data switch"
                                   tabindex="-1"
                                   data-toggle="trigger"
                                   href="#<?= $block->escapeUrl($alias); ?>"
                                   id="tab-label-<?= $block->escapeHtmlAttr($alias); ?>-title">
                                    <?= /* @noEscape */
                                    $label ?>
                                </a>
                            </div>
                            <button class="review-button action-review" type="button"  data-trigger="trigger"><?= __("Add review"); ?></button>
                        </div>
                        <div class="data item content"
                             aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias); ?>-title"
                             id="<?= $block->escapeHtmlAttr($alias); ?>" data-role="content" >
                            <?= /* @noEscape */
                            $html ?>
                        </div>
                    <?php endif;?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
                 {
                    "*": {
                      "BaseAutoSound_Catalog/js/readmore-options": {}
                        }
                  }
</script>
