<?php
/*
* BaseAutoSound FormReviews product review template.
*
*@author Hrytsuk Walentun vgritsukm@gmail.com
*@copyright 2020 zevsi
*/

/** @var \Magento\Review\Block\Product\Review $block */
?>
<div class="form-content-review"
     data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('Close'),
                class: 'action-review'
            }]
        }}">
    <?= $block->getChildHtml(); ?>
</div>
<div id="product-review-container" data-role="product-review"></div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()); ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
