<?php
/*
* BaseAutoSound FormReviews product  form template.
*
*@author Hrytsuk Walentun vgritsukm@gmail.com
*@copyright 2020 zevsi
*/

/* @var \Magento\Wishlist\Block\Link $block */
?>
<li class="link wishlist" data-bind="scope: 'wishlist'">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>><?= $block->escapeHtml($block->getLabel()) ?>
        <!-- ko if: wishlist().counter -->
        <span class="counter qty" data-bind="text: wishlist().count, css: {'no-display': !wishlist().count}"></span>    </a>
    <!-- /ko -->
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
